;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Fireball",DevComment="")
+GameplayTagList=(Tag="Ability.Firewall",DevComment="")
+GameplayTagList=(Tag="Ability.FirewallMove",DevComment="")
+GameplayTagList=(Tag="Ability.Flamethrower",DevComment="")
+GameplayTagList=(Tag="Effect.Ignite",DevComment="")
+GameplayTagList=(Tag="Event.Applied",DevComment="")
+GameplayTagList=(Tag="Event.Cast",DevComment="")
+GameplayTagList=(Tag="Event.Crit",DevComment="")
+GameplayTagList=(Tag="Event.Ended",DevComment="")
+GameplayTagList=(Tag="Event.Finish",DevComment="")
+GameplayTagList=(Tag="Event.Overlap",DevComment="")
+GameplayTagList=(Tag="Event.Removed",DevComment="")
+GameplayTagList=(Tag="Event.TargetHit",DevComment="")
+GameplayTagList=(Tag="Event.Tick",DevComment="")
+GameplayTagList=(Tag="Event.UnitDeath",DevComment="")

